-- Phase 1 identity hardening: rebuild canonical user_identity table with credentials
ALTER TABLE doctor DROP CONSTRAINT IF EXISTS fk_doctor_identity;
ALTER TABLE patient DROP CONSTRAINT IF EXISTS fk_patient_identity;

DROP TABLE IF EXISTS user_identity;

CREATE TABLE user_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_identity_email UNIQUE (email),
    CONSTRAINT uq_user_identity_email_role UNIQUE (email, role),
    CONSTRAINT chk_user_identity_role CHECK (role IN ('DOCTOR', 'PATIENT'))
);

-- Normalize historical email casing to ensure uniqueness before copying data
UPDATE doctor SET email = LOWER(TRIM(email));
UPDATE patient SET email = LOWER(TRIM(email));

INSERT INTO user_identity (email, password_hash, role, is_active, created_at, updated_at)
SELECT
    d.email,
    COALESCE(
        NULLIF(TRIM(d.password), ''),
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOHiOVFnk3Z4yKc0/4B2O8abw5Kc8p1g2'
    ),
    'DOCTOR',
    TRUE,
    COALESCE(d.created_at, CURRENT_TIMESTAMP),
    COALESCE(d.updated_at, d.created_at, CURRENT_TIMESTAMP)
FROM doctor d;

INSERT INTO user_identity (email, password_hash, role, is_active, created_at, updated_at)
SELECT
    p.email,
    COALESCE(
        NULLIF(TRIM(p.password), ''),
        '$2a$10$7EqJtq98hPqEX7fNZaFWoOHiOVFnk3Z4yKc0/4B2O8abw5Kc8p1g2'
    ),
    'PATIENT',
    TRUE,
    COALESCE(p.created_at, CURRENT_TIMESTAMP),
    COALESCE(p.updated_at, p.created_at, CURRENT_TIMESTAMP)
FROM patient p
WHERE NOT EXISTS (
    SELECT 1 FROM user_identity ui WHERE ui.email = p.email
);

ALTER TABLE doctor
    ADD CONSTRAINT fk_doctor_identity FOREIGN KEY (email, role)
        REFERENCES user_identity (email, role);

ALTER TABLE patient
    ADD CONSTRAINT fk_patient_identity FOREIGN KEY (email, role)
        REFERENCES user_identity (email, role);
